const GET_COUNTRIES = "GET_COUNTRIES"

const SEARCH_COUNTRIES = "SEARCH_COUNTRIES"

const POST_ACT = "POST_ACT"

const ORDER_AND_FILTER = "ORDER_AND_FILTER"

module.exports = {
    GET_COUNTRIES,
    SEARCH_COUNTRIES,
    POST_ACT,
    ORDER_AND_FILTER
    
}