export const GET_COUNTRIES = "GET_COUNTRIES"

export const SEARCH_COUNTRIES = "SEARCH_COUNTRIES"

export const COUNTRIES_ACTIVITY = "COUNTRIES_ACTIVITY"

export const ORDER_AND_FILTER = "ORDER_AND_FILTER"

